version: 2
updates:
  # Laravel Composer dependencies
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "laravel/framework"
        versions: ["11.x"]
    labels:
      - dependencies
    commit-message:
      prefix: "🔄 Dependency Update —"
      include: scope

  # GitHub Actions workflow updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - dependencies
    commit-message:
      prefix: "🔄 Dependency Update —"
      include: scope
